services:
  - type: web
    name: kanban-api
    env: php
    buildCommand: composer install --no-interaction
    startCommand: php artisan serve --port=$PORT
    plan: free
    healthCheckPath: /api/boards